name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clean up previous build
      run: rm -rf build
    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build C++ Project
      run: cmake --build build
